site_name: Learn C++
site_url: https://CL0001.github.io/learn-cplusplus/
theme:
  name: material
  palette:
    scheme: slate
    primary: deep orange
    accent: indigo
  features:
    - content.code.copy

extra_css:
  - style/extra.css

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - admonition
  - pymdownx.details